# Generated by Django 3.1.3 on 2020-11-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
