# Generated by Django 3.1.3 on 2020-11-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='an',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='s1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='s2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='s3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='tcm',
            field=models.IntegerField(default=0),
        ),
    ]
