# Generated by Django 3.1.3 on 2020-11-16 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_auto_20201116_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=3)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.season')),
            ],
        ),
        migrations.CreateModel(
            name='MissionTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.tile')),
            ],
        ),
    ]
