# Generated by Django 3.1.3 on 2020-11-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_missiontile_season_tile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='tiles',
            field=models.ManyToManyField(to='missions.Tile'),
        ),
    ]
