# Generated by Django 3.1.3 on 2020-11-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_mission_tiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='an',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='s3',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='tcm',
        ),
        migrations.AddField(
            model_name='mission',
            name='seasons',
            field=models.ManyToManyField(to='missions.Season'),
        ),
    ]
