# Generated by Django 3.1.3 on 2020-11-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_auto_20201116_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionTile',
        ),
    ]
