# Generated by Django 3.1.3 on 2020-11-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_mission_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
