# Generated by Django 3.1.3 on 2020-11-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0009_auto_20201117_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='num_tiles',
        ),
    ]
